<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net20;net8.0</TargetFrameworks>
    <AssemblyName>Pppp.Tests</AssemblyName>
    <RootNamespace>Pppp.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Pppp.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net20'">
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net20" Version="1.0.3" PrivateAssets="All" />
  </ItemGroup>
</Project>
