[tool.bumpversion]
current_version = "0.0.0"
tag_name = "cs-v{new_version}"
commit = true
tag = true
message = "chore: bump version (csharp)"

[[tool.bumpversion.files]]
filename = "csharp/Pppp.csproj"
search = "<Version>{current_version}</Version>"
replace = "<Version>{new_version}</Version>"
