[tool.bumpversion]
current_version = "0.0.0"
tag_name = "py-v{new_version}"
commit = true
tag = true
message = "chore: bump version (python)"

[[tool.bumpversion.files]]
filename = "pyproject.toml"
search = 'version = "{current_version}"'
replace = 'version = "{new_version}"'
